project:
  type: website
  output-dir: docs

website:
  title: "Reference Documentation"
navbar:
  left:
    - href: index.qmd
      text: "About"
    - href: a-vast-how-to.qmd
      text: "How to Use VAST"
    - href: stat-stuff.qmd
      text: "Statistical Stuff I Should Know"
    - href: math-tips.qmd
      text: "Math Refresher"
    - href: mvstats.qmd
      text: "Multivariate Stats Class Notes"

format:
  html: 
    theme: lux
    font-family: serif;