project:
  type: website
  output-dir: docs

website:
  title: "Reference Documentation"
navbar:
  left:
    - href: index.qmd
      text: "About"
    - href: stat-stuff.qmd

format:
  html: 
    theme: lux
    css: styles.css
    toc: true
    
