---
title: "Janelle L. Morano's References"
about: 
  template: jolla
---

# Project Overview

**Ph.D. Dissertation: Forecasting and Adapting Fisheries Management for the Future:Quantifying Spatio-Temporal Responses of Forage Fishes to Climate Change**

Where fish are and when they move depends on ideal habitat for feeding and spawning. As human-induced climate change is changing the marine ecosystem and impacts fishing communities [such that our historical understanding is not indicative of the future], fisheries management demands a more rapid and dynamic response. Forage species are an important link in the ecosystem because they are consumers of plankton and prey to managed and protected species of fishes, marine mammals, and birds, but we often lack information on the populations of most forage species. Quantitative metrics show that many marine species distributions are shifting and expanding along the US east coast as water temperatures warm, but less attention has been paid to quantifying local increases or decreases in distribution from the ecosystem interaction of abiotic and biotic conditions (e.g., water temperature, depth, prey availability) that may impact fishing and our understanding of the ecosystem and species adaptations, and particularly for forage fishes. Therefore, I will address three major questions: 

1.	Where are the forage fish along the US east coast currently; how and why has their distribution changed? 
1.	Where will they be in future?
1.	How can species distribution forecasts be incorporated into the current management process to adapt to anticipated distribution changes?


My research is supported by the NMFS-Sea Grant Population and Ecosystem Dynamics Fellowship and the New York Department of Environmental Conservation.



## Current Project
Currently, I am building a spatio-temporal model of Atlantic menhaden to understand if menhaden distribution has shifted northward and/or offshore in recent years and evaluate the influence of water temperature and prey availability. 
